---
- name: Run script on host
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_user: SYSTEM
  become_method: runas

  tasks:

    - name: Check running services
      ansible.windows.win_service_info:
      register: services

    - name: Set fact with services that are running state
      set_fact:
        running_services: "{{ services.services | selectattr('state', 'equalto', 'Running') | map(attribute='name') | list }}"

    - name: Debug running services
      debug:
        var: running_services