- name: Chocolatey Tasks
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: false

  tasks:

    - name: Install Chocolatey package
      when: task == "install"
      ansible.builtin.import_role:
        name: eingram23.windows.chocolatey
        tasks_from: install
