---
- name: Run tasks
  hosts: "veeam.local.lan"
  gather_facts: false
  become: true

  vars:
    path: \temp\test.txt

  tasks:

    - ansible.windows.win_stat:
        path: "{{ item }}{{ path }}"
      loop:
        - "c:"
        - "d:"
      register: file_check

    - fail:
      when: file_check is not defined
      
    - set_fact:
        test: "{{ item.stat.path }}"
      when: item.stat.exists
      loop: "{{ file_check.results }}"

    - debug: var=test

    - fail:
      when: test is not defined