- name: Reboot Windows machine
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true

  tasks:

    - name: Reboot windows host
      ansible.windows.win_reboot:
        msg: Reboot via Ansible
