- name: Send a magic Wake-on-LAN packet
  community.general.wakeonlan:
    mac: '{{ mac_address | default("00:00:00:00:00:00") }}'
    broadcast: 10.1.0.255
  delegate_to: localhost
  become: false

- name: Wait up to 60 seconds
  ansible.builtin.wait_for_connection:
    delay: 1
    timeout: 60
