---
- name: Add firewall rule
  community.windows.win_firewall_rule:
    name: "{{ rule_name }}"
    localport: "{{ fw_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol }}"
    state: present
    enabled: true
