---
- name: Open firewall port
  community.windows.win_firewall_rule:
    name: Grafana Agent
    localport: 12345
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true

- name: Uninstall windows_exporter if present
  ansible.windows.win_package:
    product_id: '{7D6689D4-C52B-46BC-A492-189212FD07D1}'
    state: absent

- name: Download grafana agent installer to host
  ansible.windows.win_get_url:
    url: https://github.com/grafana/agent/releases/download/{{ ver }}/grafana-agent-installer.exe.zip
    dest: c:\temp\grafana-agent-installer.exe.zip

- name: Unzip installer
  community.windows.win_unzip:
    src: c:\temp\grafana-agent-installer.exe.zip
    dest: c:\temp\grafana-agent-installer-{{ ver }}
    creates: c:\temp\grafana-agent-installer-{{ ver }}
    delete_archive: false

- name: Run installer
  ansible.windows.win_shell: |
    c:\temp\grafana-agent-installer-{{ ver }}\grafana-agent-installer.exe /S

- name: Create agent config on host
  ansible.windows.win_template:
    src: agent-config.yaml.j2
    dest: c:\program files\grafana agent\agent-config.yaml

- name: Modify registry to change http_server_address
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Grafana Agent
    name: ImagePath
    data: '"C:\Program Files\Grafana Agent\grafana-agent-windows-amd64.exe" -server.http.address="0.0.0.0:12345" -config.file="C:\Program Files\Grafana Agent\agent-config.yaml"'
    type: expandstring
  notify: Restart grafana agent
