---
- name: Close firewall port
  community.windows.win_firewall_rule:
    name: Grafana Agent
    localport: 12345
    action: allow
    direction: in
    protocol: tcp
    state: absent

- name: Check for uninstall.exe
  ansible.windows.win_stat:
    path: C:\Program Files\Grafana Agent\Uninstall.exe
  register: uninstall

- name: Uninstall grafana agent
  when: uninstall.stat.exists
  ansible.windows.win_package:
    path: C:\Program Files\Grafana Agent\Uninstall.exe
    product_id: Grafana Agent
    arguments: /S
    state: absent
  notify: Reboot

- name: Clean up Grafana Agent folder
  ansible.windows.win_file:
    path: C:\Program Files\Grafana Agent
    state: absent
